
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzgrvouzygsssvkhddqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Z3J2b3V6eWdzc3N2a2hkZHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjU4NDYsImV4cCI6MjA2MzUwMTg0Nn0.8E0uIfQN0KseDw6bQQzYGfpiDFysdjHQ01atD9bmp8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
